# GA1-240201064-04-AA1-EV05 – Fundamentos en Pandas Explorando los DataFrame

**Aprendiz:** Yojhann Vasquez  
**Actividad:** EV05  
**Tema:** Exploración de DataFrames con Pandas  
**Herramienta utilizada:** Jupyter Notebook en entorno local con Python

---

## Objetivo

Explorar la creación, manipulación y análisis básico de datos utilizando **DataFrames en Pandas**, comprendiendo su utilidad en proyectos de análisis de datos.

## Contenido del notebook

1. Importación de la librería Pandas  
2. Creación de un DataFrame  
3. Exploración de la estructura de datos  
4. Selección de columnas y filas  
5. Agregar nuevas columnas  
6. Filtrado de información  
7. Ordenamiento de datos  
8. Cálculos estadísticos  
9. Exportación de datos  
10. Reflexión final

In [1]:
import pandas as pd

## 1. Importación de Pandas

En este paso se importa la librería **Pandas**, la cual es ampliamente utilizada en Python para el análisis y manipulación de datos.

Se utiliza el alias `pd` para simplificar su escritura en el código.

In [2]:
datos = {
    "Nombre": ["Ana", "Luis", "Carlos", "María", "Sofía"],
    "Edad": [22, 25, 30, 28, 21],
    "Ciudad": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena"],
    "Carrera": ["Ingeniería", "Diseño", "Administración", "Contabilidad", "Psicología"]
}

df = pd.DataFrame(datos)
df

   Nombre  Edad        Ciudad         Carrera
0     Ana    22        Bogotá      Ingeniería
1    Luis    25      Medellín          Diseño
2  Carlos    30          Cali  Administración
3   María    28  Barranquilla    Contabilidad
4   Sofía    21     Cartagena      Psicología

## 2. Creación de un DataFrame

En este ejercicio se crea un **DataFrame** a partir de un diccionario de Python.

Cada clave representa una **columna**, mientras que cada lista contiene los valores correspondientes a esa columna.

El DataFrame organiza la información en forma de tabla, lo cual facilita su exploración y análisis.

In [3]:
df.head()

   Nombre  Edad        Ciudad         Carrera
0     Ana    22        Bogotá      Ingeniería
1    Luis    25      Medellín          Diseño
2  Carlos    30          Cali  Administración
3   María    28  Barranquilla    Contabilidad
4   Sofía    21     Cartagena      Psicología

## 3. Visualización inicial de datos

Con el método `head()` se visualizan las primeras filas del DataFrame.

Esto es útil para revisar rápidamente si la estructura y el contenido de los datos son correctos.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nombre   5 non-null      object
 1   Edad     5 non-null      int64
 2   Ciudad   5 non-null      object
 3   Carrera  5 non-null      object
dtypes: int64(1), object(3)
memory usage: 292.0+ bytes

## 4. Información general del DataFrame

El método `info()` permite observar información general sobre el DataFrame, como:

- número de filas
- número de columnas
- nombres de las columnas
- tipos de datos
- cantidad de valores no nulos

Este análisis ayuda a comprender mejor la estructura interna de los datos.

In [5]:
df.describe()

            Edad
count   5.000000
mean   25.200000
std     3.834058
min    21.000000
25%    22.000000
50%    25.000000
75%    28.000000
max    30.000000

## 5. Estadísticas descriptivas

El método `describe()` genera un resumen estadístico de las columnas numéricas del DataFrame.

Entre los valores mostrados se encuentran:

- cantidad de datos
- promedio
- desviación estándar
- valor mínimo
- valor máximo

Esto facilita una exploración inicial de la información numérica.

In [6]:
df["Nombre"]

0       Ana
1      Luis
2    Carlos
3     María
4     Sofía
Name: Nombre, dtype: object

## 6. Selección de una columna

Aquí se selecciona únicamente la columna **Nombre** del DataFrame.

Esto permite trabajar específicamente con una sola variable de la tabla.

In [7]:
df[["Nombre", "Edad"]]

   Nombre  Edad
0     Ana    22
1    Luis    25
2  Carlos    30
3   María    28
4   Sofía    21

## 7. Selección de varias columnas

En este caso se extraen las columnas **Nombre** y **Edad**.

Esto resulta útil cuando se desea analizar solamente ciertos datos sin mostrar toda la tabla.

In [8]:
df.loc[0]

Nombre            Ana
Edad               22
Ciudad         Bogotá
Carrera    Ingeniería
Name: 0, dtype: object

## 8. Selección de una fila

El método `loc[]` permite seleccionar filas específicas utilizando su índice.

En este ejemplo se accede al primer registro del DataFrame.

In [9]:
df["Salario"] = [1500000, 1800000, 2500000, 2200000, 1600000]
df

   Nombre  Edad        Ciudad         Carrera  Salario
0     Ana    22        Bogotá      Ingeniería  1500000
1    Luis    25      Medellín          Diseño  1800000
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000
4   Sofía    21     Cartagena      Psicología  1600000

## 9. Agregar una nueva columna

En este paso se agrega una nueva columna llamada **Salario**.

Esto demuestra que los DataFrames permiten incorporar nueva información de forma sencilla y flexible.

In [10]:
df[df["Edad"] > 24]

   Nombre  Edad        Ciudad         Carrera  Salario
1    Luis    25      Medellín          Diseño  1800000
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000

## 10. Filtrado por condición numérica

Aquí se filtran únicamente las filas donde la edad es mayor a 24 años.

Los filtros son muy útiles para extraer subconjuntos de información dentro de un conjunto de datos más grande.

In [11]:
df[df["Ciudad"] == "Bogotá"]

  Nombre  Edad  Ciudad     Carrera  Salario
0    Ana    22  Bogotá  Ingeniería  1500000

## 11. Filtrado por condición de texto

En este ejemplo se filtran los registros cuya ciudad sea **Bogotá**.

Esto permite localizar información puntual dentro del DataFrame.

In [12]:
df.sort_values("Edad")

   Nombre  Edad        Ciudad         Carrera  Salario
4   Sofía    21     Cartagena      Psicología  1600000
0     Ana    22        Bogotá      Ingeniería  1500000
1    Luis    25      Medellín          Diseño  1800000
3   María    28  Barranquilla    Contabilidad  2200000
2  Carlos    30          Cali  Administración  2500000

## 12. Ordenamiento de datos

Con `sort_values()` se pueden ordenar los datos según una columna específica.

En este caso, las personas se ordenan de menor a mayor según la edad.

In [14]:
df["Salario"].mean()

np.float64(1920000.0)

## 13. Cálculo del promedio

Con el método `mean()` se calcula el promedio de la columna **Salario**.

Este tipo de operación es útil para realizar análisis estadísticos básicos.

In [15]:
df["Salario"].max()

np.int64(2500000)

## 14. Valor máximo

Con el método `max()` se obtiene el valor más alto de la columna **Salario**.

Esto permite identificar el valor máximo dentro de un conjunto de datos numéricos.

In [17]:
df.to_csv("personas.csv", index=False)

## 15. Exportación del DataFrame

En este paso se exporta el DataFrame a un archivo CSV llamado `personas.csv`.

Esto permite guardar la información para usarla posteriormente en otros análisis o herramientas.

In [18]:
df

   Nombre  Edad        Ciudad         Carrera  Salario
0     Ana    22        Bogotá      Ingeniería  1500000
1    Luis    25      Medellín          Diseño  1800000
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000
4   Sofía    21     Cartagena      Psicología  1600000

In [19]:
# ejersicio adicional Mostrar solo las personas con salario mayor a 1.700.000
df[df["Salario"] > 1700000]

   Nombre  Edad        Ciudad         Carrera  Salario
1    Luis    25      Medellín          Diseño  1800000
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000

## 16. Ejercicio adicional

En este ejercicio adicional se filtran las personas cuyo salario es mayor a **1.700.000**.

Esto refuerza el uso de condiciones para seleccionar información específica dentro del DataFrame.

In [20]:
# Ordenar por salario de mayor a menor
df.sort_values("Salario", ascending=False)

   Nombre  Edad        Ciudad         Carrera  Salario
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000
1    Luis    25      Medellín          Diseño  1800000
4   Sofía    21     Cartagena      Psicología  1600000
0     Ana    22        Bogotá      Ingeniería  1500000

In [21]:
# ejersicio final: Ordenar por salario de mayor a menor
df.sort_values("Salario", ascending=False)

   Nombre  Edad        Ciudad         Carrera  Salario
2  Carlos    30          Cali  Administración  2500000
3   María    28  Barranquilla    Contabilidad  2200000
1    Luis    25      Medellín          Diseño  1800000
4   Sofía    21     Cartagena      Psicología  1600000
0     Ana    22        Bogotá      Ingeniería  1500000

## 17. Ordenamiento descendente

En este caso se ordena la columna **Salario** de mayor a menor utilizando el parámetro `ascending=False`.

Esto permite identificar rápidamente los registros con los valores más altos.

# Pregunta reflexiva final

## ¿Cómo contribuye el uso de DataFrame en Pandas a la eficiencia y comprensión de los datos en un proyecto de análisis?

El uso de **DataFrames en Pandas** contribuye significativamente a la eficiencia y comprensión de los datos, ya que permite organizar la información en una estructura tabular clara, similar a una hoja de cálculo o una base de datos.

Además, facilita tareas como:

- visualizar datos rápidamente,
- seleccionar columnas o filas específicas,
- aplicar filtros,
- ordenar información,
- realizar cálculos estadísticos,
- exportar datos a otros formatos.

Gracias a esto, el analista puede trabajar de forma más organizada, reducir errores y comprender mejor los datos antes de tomar decisiones dentro de un proyecto de análisis.

# Conclusión

En esta actividad se trabajó con los conceptos fundamentales de los **DataFrames en Pandas**, permitiendo comprender cómo crear, visualizar, filtrar, ordenar y analizar datos de forma práctica.

El uso de esta estructura es esencial en ciencia de datos, ya que facilita la manipulación y comprensión de grandes volúmenes de información.